### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribute 'custom_fwd'

### ISSUE THREAD

**Issue by linhaojia13** [guochengqian/PointNeXt#32]
Thank you for your open codes!
It seems that the version of the torch or cuda is not mismatched. 
```
script/main_segmentation.sh: line 34: nvcc: command not found
MAC235
4
Traceback (most recent call last):
  File "examples/segmentation/main.py", line 18, in <module>
    from openpoints.dataset import build_dataloader_from_cfg, get_scene_seg_features, get_class_weights
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/dataset/__init__.py", line 6, in <module>
    from .scanobjectnn import *
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/dataset/scanobjectnn/__init__.py", line 1, in <module>
    from .scanobjectnn import ScanObjectNNHardest
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/dataset/scanobjectnn/scanobjectnn.py", line 5, in <module>
    from openpoints.models.layers import fps
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/models/__init__.py", line 5, in <module>
    from .backbone import *
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/models/backbone/__init__.py", line 1, in <module>
    from .pointnetv2 import PointNet2Encoder, PointNet2Decoder, PointNetFPModule
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/models/backbone/pointnetv2.py", line 16, in <module>
    from ..layers import furthest_point_sample, random_sample, LocalAggregation, three_interpolation, create_convblock1d
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/models/layers/__init__.py", line 7, in <module>
    from .group import grouping_operation, gather_operation, create_grouper
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/models/layers/group.py", line 76, in <module>
    class GroupingOperation(Function):
  File "/home/lhj/pointcloud/PointNeXt-master/examples/segmentation/../../openpoints/models/layers/group.py", line 79, in GroupingOperation
    @torch.cuda.custom_fwd(cast_inputs=torch.float32)
AttributeError: module 'torch.cuda' has no attribute 'custom_fwd'
```

I query the version via  `conda list -f cudatoolkit` and `conda list -f pytorch` , and it returns: 
```
# packages in environment at /home/lhj/anaconda3/envs/openpoints:
#
# Name                    Version                   Build  Channel
cudatoolkit               11.1.74              h6bb024c_0    nvidia
```
```
# packages in environment at /home/lhj/anaconda3/envs/openpoints:
#
# Name                    Version                   Build  Channel
pytorch                   1.10.1          py3.7_cuda11.1_cudnn8.0.5_0    pytorch
```
The cuda version is 11.1 and the pytorch version is 1.10, which is same as the requirement. Therefore, the version of the pytorch and cuda is OK. 

How can I fix this problem?

**Comment by linhaojia13** [comment]
I comment the decorator in the `class GroupingOperation(Function)`, and the training can be conducted normally.
```
class GroupingOperation(Function):

    @staticmethod
    # @torch.cuda.custom_fwd(cast_inputs=torch.float32)
    def forward(ctx, features: torch.Tensor, idx: torch.Tensor) -> torch.Tensor:
        """
        :param ctx:
        :param features: (B, C, N) tensor of features to group
        :param idx: (B, npoint, nsample) tensor containing the indicies of features to group with
        :return:
            output: (B, C, npoint, nsample) tensor
        """
        assert features.is_contiguous()
        assert idx.is_contiguous()

        B, nfeatures, nsample = idx.size()
        _, C, N = features.size()
        output = torch.cuda.FloatTensor(B, C, nfeatures, nsample, device=features.device)

        pointnet2_cuda.group_points_wrapper(B, C, N, nfeatures, nsample, features, idx, output)

        ctx.for_backwards = (idx, N)
        return output
```
What is the usage of this decorator?

**Comment by linhaojia13** [comment]
Thanks.
