### ISSUE TITLE
OOM when training ASSANet-L in a single A100 (40G)

### ISSUE THREAD

**Issue by linhaojia13** [guochengqian/PointNeXt#33]
I try to train the ASSANet-L in a single A100 (40G memory) via  `CUDA_VISIBLE_DEVICES=3 bash script/main_segmentation.sh cfgs/s3dis/assanet-l.yaml`. However, it return the OOM error.

```
[08/23 23:12:49 S3DIS]: length of training dataset: 6120
  0%|                                                                                                                | 0/191 [00:30<?, ?it/s]
Traceback (most recent call last):
  File "examples/segmentation/main.py", line 528, in <module>
    main(0, cfg)
  File "examples/segmentation/main.py", line 151, in main
    train_one_epoch(model, train_loader, criterion, optimizer, scheduler, epoch, cfg)
  File "examples/segmentation/main.py", line 258, in train_one_epoch
    loss.backward()
  File "/home/lhj/anaconda3/envs/openpoints/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/lhj/anaconda3/envs/openpoints/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 4.95 GiB (GPU 0; 39.44 GiB total capacity; 28.40 GiB already allocated; 4.88 GiB free; 32.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

wandb: Waiting for W&B process to finish, PID 1424604... (failed 1). Press ctrl-c to abort syncing.
wandb:
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 2 other file(s)
wandb: Synced s3dis-train-assanet-l-ngpus1-seed1505-20220823-231215-GuXKGc4ow6CF6ZymcSXg6V: https://wandb.ai/linhaojia/PointNeXt-S3DIS/runs/3qy19fo9
wandb: Find logs at: ./wandb/run-20220823_231216-3qy19fo9/logs/debug.log
wandb:
```

What hardwares did you use to train ASSANet-L? Should I use more GPUs?

**Comment by linhaojia13** [comment]
Thank you very much. Looking forward to your solution.

**Comment by guochengqian** [comment]
hi @linhaojia13 

i found there is an issue with assanet-l. i will update it later.

**Comment by linhaojia13** [comment]
> hi @linhaojia13
> 
> i found there is an issue with assanet-l. i will update it later.

Thanks. Looking forward to your updation.

**Comment by guochengqian** [comment]
the bug is fixed. i am rerunning to reproduce results
