### ISSUE TITLE
The problem about multi-GPUs training,"TypeError: main() takes 2 positional arguments but 63 were given"

### ISSUE THREAD

**Issue by wang88256187** [guochengqian/PointNeXt#8]
Traceback (most recent call last):
  File "examples/segmentation/main.py", line 526, in <module>
    mp.spawn(main, nprocs=cfg.world_size, args=(cfg))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
TypeError: main() takes 2 positional arguments but 63 were given

**Comment by guochengqian** [comment]
please comment with the command line you used

**Comment by wang88256187** [comment]
> please comment with the command line you used

python examples/segmentation/main.py --cfg cfgs/s3dis/pointnext-s.yaml,
I have fine the bug at:
 File "examples/segmentation/main.py", line 526, in mp.spawn(main, nprocs=cfg.world_size, args=(cfg))
where the right way is "mp.spawn(main, nprocs=cfg.world_size, args=(cfg,))". it is just a comma that cause this problem.
Thinks for your briliant job.

**Comment by guochengqian** [comment]
thank you for letting me know this. this will be solved at the next update with shapenetpart code.

**Comment by guochengqian** [comment]
I am pushing my collaborator to release the code asap. Iam not sure when he could finish.
