### ISSUE TITLE
Could not compile openpoints with cuda11.3

### ISSUE THREAD

**Issue by whuhxb** [guochengqian/PointNeXt#92]
Hi, I could create the openpoints environment using source install.sh, but I could not compile openpoints with cuda11.3 now. The bugs are the following. Could you please help me out?

/cm/shared/apps/cuda11.3/toolkit/11.3.0/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  139 | #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    'build_ext': BuildExtension
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
    build_ext.build_extensions(self)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 565, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/export/home2/hanxiaobing/anaconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by guochengqian** [comment]
error said:  error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! 
please downsample GCC

**Comment by sheshap** [comment]
Commenting a couple of lines as mentioned in the below link can support gcc > 10. It worked for me with gcc 11.

https://github.com/NVIDIA/nccl/issues/650#issuecomment-1145173577
