### ISSUE TITLE
Bugs during testing on S3DIS dataset

### ISSUE THREAD

**Issue by whuhxb** [guochengqian/PointNeXt#95]
Hi, 
   Have you ever met this bug during testing on S3DIS with pointnext-xl.yaml?

Test on 67-th cloud [53]/[54]]: 100%|██████████| 54/54 [00:16<00:00,  3.32it/s]
Traceback (most recent call last):
  File "examples/segmentation/main.py", line 734, in <module>
    main(0, cfg)
  File "examples/segmentation/main.py", line 334, in main
    dist.destroy_process_group()
  File "/export/home2/***/anaconda3/envs/openpoints/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 775, in destroy_process_group
    assert pg is not None
AssertionError

**Comment by whuhxb** [comment]
> It looks like some errors in the distributed gpus. I haven't come across the issue before. Could you share more details on it?

I have commented the "dist.destroy_process_group()". I guess it's caused by the release of multiprocessing.

**Comment by guochengqian** [comment]
thanks. commented this line.

**Comment by Chengwang-an** [comment]
Has the problem been resolved ？
